In [1]:
import numpy as np
import pandas as pd

from ols_bootstrap.pairs import PairsBootstrap
from ols_bootstrap.residual import ResidualBootstrap
from ols_bootstrap.wild import WildBootstrap

pd.options.display.float_format = '{:20,.5f}'.format  ### Setting pd to have a numerical precision up to 5 decimal points

In [2]:
df = pd.read_csv('./balance2018.csv')
df = df[df['sales_clean'] != 0]
df = df[['sales_clean', 'tanass_clean', 'tax']]
df = df.dropna(subset=['tanass_clean', 'tax'])

df_scaled = df.applymap(lambda x: np.log(x + 1))

/home/phamv/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (66) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [3]:
df_sample = df_scaled.sample(n=1000, replace=False, random_state=42)

Y_data = pd.DataFrame(df_sample.iloc[:, 0])
X_data = pd.DataFrame(df_sample.iloc[:, 1:])

In [4]:
wb_mam = WildBootstrap(Y_data, X_data, reps = 1000, from_distro = "mammen", seed = 42)  # seed = None, se_type = 'hc3' and ci_type = 'bc' are the default options for these arguments.
wb_mam.simple_ols_fit()

In [5]:
wb_mam.bp_test()

(56.702329897241775,
 4.866822501071809e-13,
 29.965208597086683,
 2.3036035267823517e-13)

In [8]:
wb_mam.bp_test(robust = False)

(126.38966088406505,
 3.5878465000474625e-28,
 29.965208597086807,
 2.3036035267820897e-13)

In [9]:
wb_mam.white_test()

(200.37774678235587,
 2.358326510723417e-41,
 49.81739302531628,
 4.114335824295388e-46)

In [4]:
wb_mam = WildBootstrap(Y_data, X_data, reps = 1000, from_distro = "mammen", seed = 42)  # seed = None, se_type = 'hc3' and ci_type = 'bc' are the default options for these arguments.
wb_mam.fit()
wb_mam.summary()

## Default SE on the original OLS is HC3, default CI on bootstrapped parameter is BC. 

That is by default se_type = 'hc3', ci_type = 'bc'.

The default seed value is None. For reproducability, use an integer of your choice. 

In [4]:
psb = PairsBootstrap(Y_data, X_data, reps = 1000, se_type='hc3', ci_type = 'bc', seed = 42)  # seed = None, se_type = 'hc3' and ci_type = 'bc' are the default options for these arguments.
psb.fit()

In [5]:
psb_t = PairsBootstrap(Y_data, X_data, reps = 1000, ci_type = 'studentized', seed = 42) 
psb_t.fit()

In [6]:
rsb_not_scaled = ResidualBootstrap(Y_data, X_data, reps = 1000, scale_resid_bool  = False, seed = 42)
rsb_not_scaled.fit()

In [7]:
rsb = ResidualBootstrap(Y_data, X_data, reps = 1000, seed = 42)
rsb.fit()

In [8]:
rsb_t = ResidualBootstrap(Y_data, X_data, ci_type='studentized', reps = 1000, scale_resid_bool = True, seed = 42)
rsb_t.fit()

In [9]:
wb_unif = WildBootstrap(Y_data, X_data, reps = 1000, from_distro = "uniform", seed = 42)
wb_unif.fit()

In [10]:
wb_stdn = WildBootstrap(Y_data, X_data, reps = 1000, from_distro = "standard_normal", seed = 42)
wb_stdn.fit()

In [11]:
wb_rad_not_scaled = WildBootstrap(Y_data, X_data, reps = 1000, scale_resid_bool = False, from_distro = "rademacher", seed = 42)
wb_rad_not_scaled.fit()

In [12]:
wb_rad = WildBootstrap(Y_data, X_data, reps = 1000, from_distro = "rademacher", seed = 42)
wb_rad.fit()

In [13]:
wb_rad_bca = WildBootstrap(Y_data, X_data, reps = 1000, ci_type='bca', from_distro = "rademacher", seed = 42)
wb_rad_bca.fit()

In [14]:
wb_rad_t = WildBootstrap(Y_data, X_data, reps = 1000, ci_type='studentized',  from_distro = "rademacher", seed = 42)
wb_rad_t.fit()

In [15]:
wb_rad_emp = WildBootstrap(Y_data, X_data, reps = 1000, ci_type='empirical', from_distro = "rademacher", seed = 42)
wb_rad_emp.fit()

In [16]:
wb_rad_perc = WildBootstrap(Y_data, X_data, reps = 1000, ci_type='percentile', from_distro = "rademacher", seed = 42)
wb_rad_perc.fit()

In [17]:
wb_rad_basic = WildBootstrap(Y_data, X_data, reps = 1000, ci_type='basic', from_distro = "rademacher", seed = 42)
wb_rad_basic.fit()

In [18]:
wb_webb4 = WildBootstrap(Y_data, X_data, reps = 1000, from_distro = "webb4", seed = 42)
wb_webb4.fit()

In [19]:
wb_webb6 = WildBootstrap(Y_data, X_data, reps = 1000, from_distro = "webb6", seed = 42)
wb_webb6.fit()

In [20]:
wb_cont_mam = WildBootstrap(Y_data, X_data, reps = 1000, from_distro = "mammen_cont", seed = 42)
wb_cont_mam.fit()

In [21]:
wb_mam = WildBootstrap(Y_data, X_data, reps = 1000, from_distro = "mammen", seed = 42)
wb_mam.fit()

In [22]:
# Now: np.ndarray was supported as an input array. pd.Series, list, and tuples were also added to the supported list for an input array. 
# Before that only pd.DataFrame had been supported. 
X_data_np = X_data.to_numpy()
Y_data_np = Y_data.to_numpy()

In [23]:
wb_mam_np = WildBootstrap(Y_data_np, X_data_np, reps = 1000, from_distro = "mammen", seed = 42)
wb_mam_np.fit()

In [24]:
psb.summary()

In [25]:
psb.summary_table

ols_params avg_bs_params    bias ols_params_se bs_params_se  \
var                                                                        
const            6.0961        6.1032  0.0071        0.1392       0.1316   
tanass_clean     0.2021        0.2017  0.0004        0.0181       0.0184   
tax              0.5048        0.5038   0.001        0.0296       0.0295   

             perc_of_se_diff ci_lower ci_upper  
var                                             
const                    5.4   5.7828   6.3358  
tanass_clean           -1.93    0.169   0.2434  
tax                     0.46   0.4456   0.5639

In [26]:
psb_t.summary()

In [27]:
rsb_not_scaled.summary()

In [28]:
rsb.summary()

In [29]:
rsb_t.summary()

In [30]:
wb_unif.summary()

In [31]:
wb_stdn.summary()

In [32]:
wb_rad_not_scaled.summary()

In [33]:
wb_rad.summary()

In [34]:
wb_rad_bca.summary()

In [35]:
wb_rad_bca_jack = WildBootstrap(Y_data, X_data, reps = 1000, ci_type='bca', from_distro = "rademacher", subset_jack_ratio=0.5, seed = 42) #using partial jacknife estimation for a_hat acceleration param 
wb_rad_bca_jack.fit()
wb_rad_bca_jack.summary()

In [36]:
wb_rad_t.summary()

In [37]:
wb_rad_emp.summary()

In [38]:
wb_rad_perc.summary()

In [39]:
wb_rad_basic.summary()

In [40]:
wb_webb4.summary()

In [41]:
wb_webb6.summary()

In [42]:
wb_cont_mam.summary()

In [43]:
wb_mam.summary()

Same output for wb_mam_np as in the case for wb_mam, but the difference is the independent variables' name. wb_mam was constructed with pd.DataFrame the input which holds information about the column name. 
When it comes to wb_mam_np, it was constructed with np.ndarray as the input which DOES NOT hold info about the column name originally. Because of this, x1, x2, ...., xn were generated as alternative independent variable names. 

In [44]:
wb_mam_np.summary()

## Some useful methods were implemented (let's use it on wb_mam object of Wild Bootstrap with Mammen)

- The common in the following three methods is that either a string (if one wishes to capture one variable or ci) or 1-D like array can be provided to 'which_var' and/or 'which_ci' (the latter if exists in that object class).

### get_ci() method

#### Vanila version is when only the actual CI was used with all independent variables

In [45]:
wb_mam.get_ci()

bc                     
                              lwb                  upb
const                     5.81744              6.36415
tanass_clean              0.16574              0.23934
tax                       0.44588              0.56560

#### However, any combination of ('bc', 'bca', 'percentile) CI types could be selected and any combinations of independent variables can be chosen with 'which_ci' and 'which_var' optional arguments, respectively.

Please note that if choosing 'bca' the calculation can take a while as it uses jacknife resampling for calculating the acceleration factor

In [46]:
wb_mam.get_ci(which_ci='all', which_var='all')

bc                                       bca  \
                              lwb                  upb                  lwb   
const                     5.81744              6.36415              5.81644   
tanass_clean              0.16574              0.23934              0.16660   
tax                       0.44588              0.56560              0.44387   

                                            percentile                       
                              upb                  lwb                  upb  
const                     6.36328              5.81898              6.36552  
tanass_clean              0.24041              0.16591              0.24008  
tax                       0.56414              0.44362              0.56271

In [47]:
wb_mam.get_ci(which_ci=['bc', 'percentile'], which_var=['tax', 'const'])

bc                                percentile  \
                       lwb                  upb                  lwb   
tax                0.44588              0.56560              0.44362   
const              5.81744              6.36415              5.81898   

                            
                       upb  
tax                0.56271  
const              6.36552

In [48]:
wb_mam.get_ci(which_ci=['bca', 'bc'], which_var='tanass_clean')

bc                                       bca  \
                              lwb                  upb                  lwb   
tanass_clean              0.16574              0.23934              0.16660   

                                   
                              upb  
tanass_clean              0.24041

In [49]:
wb_mam.get_ci(which_ci='bc', which_var='tanass_clean')

bc                     
                              lwb                  upb
tanass_clean              0.16574              0.23934

### get_all_se() method

The following SE-s are calculated: 
- bootstrapped - standard error of the bootstrapped parameters
- constant - model-based OLS Standard Errors, that is, constant variance is assumed 
- HC0, HC1, HC2, HC3, HC4, HC4m, HC5 - Heteroskedasticity-Consistent Standard Errors (HCE) using sandwich estimators 

#### Vanila version is when using all indepencdent variables. 

In [50]:
#wb_mam.get_all_se()

#### A subset of independent variables can be chosen with 'which_var' argument to calculate the above-mentioned 9 SE-s

In [51]:
#wb_mam.get_all_se(which_var=['tanass_clean', 'tax'])

In [52]:
#wb_mam.get_all_se(which_var='tax')

### get_bootstrap_params() method

#### Vanila version: Returning a dataframe capturing the parameter estimate of ALL each independent variables in each (wild) bootstrap.

In [53]:
wb_mam.get_bootstrap_params()

const         tanass_clean                  tax
0                6.13846              0.20314              0.49943
1                6.23415              0.20213              0.46960
2                6.42391              0.17546              0.48686
3                6.08326              0.22741              0.48363
4                6.01685              0.19635              0.52267
..                   ...                  ...                  ...
995              6.04760              0.19344              0.53570
996              6.14364              0.24250              0.44653
997              6.17723              0.15745              0.53618
998              5.88356              0.19920              0.56767
999              5.93417              0.22947              0.47852

[1000 rows x 3 columns]

#### As usual, the desired independent variable can be chosen with 'which_var' argument

In [54]:
wb_mam.get_bootstrap_params(which_var='tax')

tax
0                0.49943
1                0.46960
2                0.48686
3                0.48363
4                0.52267
..                   ...
995              0.53570
996              0.44653
997              0.53618
998              0.56767
999              0.47852

[1000 rows x 1 columns]

In [55]:
wb_mam.get_bootstrap_params(which_var=('const', 'tanass_clean'))

const         tanass_clean
0                6.13846              0.20314
1                6.23415              0.20213
2                6.42391              0.17546
3                6.08326              0.22741
4                6.01685              0.19635
..                   ...                  ...
995              6.04760              0.19344
996              6.14364              0.24250
997              6.17723              0.15745
998              5.88356              0.19920
999              5.93417              0.22947

[1000 rows x 2 columns]

### bp_test() and white_test() methods

#### Vanila version: for bp_test() returning the robust version (proposed by Roger Koenker) of this test when the presence of the heteroscedasticity is examined on the residual of the OLS on the original sample data. For white_test(), there are no optional arguments

In [56]:
wb_mam.bp_test()

(56.702329897241775,
 4.866822501071809e-13,
 29.965208597086683,
 2.3036035267823517e-13)

In [57]:
wb_mam.white_test()

(200.37774678235587,
 2.358326510723417e-41,
 49.81739302531628,
 4.114335824295388e-46)

#### The non-robust version of bp_test() can be achieved by setting bp_test(robust = False).

In [58]:
wb_mam.bp_test(robust = False)

(126.38966088406505,
 3.5878465000474625e-28,
 29.965208597086807,
 2.3036035267820897e-13)

At each test, the first value is the calculated LM-test stats, the second is the 'LM p-value' corresponding to the LM-test stats, the third value is the F-test stats and last one is the 'F p-value'.

As it can be seen the p-values are 0, so we can rejcet the null hypothesis of homoscedasticity, and accept the alternative hypothesis that the variance of the residuals is heteroscedastic.

### Some built-in attributes

In [59]:
wb_mam.indep_varname

['const', 'tanass_clean', 'tax']

#### wb_mam.bs_params and wb_mam.get_bootstrap_params() basically output the same thing with the exception that the latter one is transposed and is in pd.DataFrame.

In [60]:
wb_mam.bs_params

array([[6.13846258, 6.2341534 , 6.42391213, ..., 6.1772337 , 5.88356481,
        5.93416761],
       [0.20314385, 0.20213401, 0.17545997, ..., 0.15744657, 0.19920325,
        0.22947161],
       [0.49943104, 0.46959608, 0.48686301, ..., 0.53617785, 0.56767433,
        0.47852104]])

In [61]:
wb_mam.orig_params

array([6.09609653, 0.20207703, 0.50475146])

In [62]:
wb_mam.bs_mean

array([6.09716622, 0.20280901, 0.50417834])

In [63]:
wb_mam.orig_se

array([0.13915933, 0.01806678, 0.0296142 ])

In [64]:
wb_mam.bs_se

array([0.1417777 , 0.01849049, 0.03062783])

In [65]:
wb_mam.bs_ci

array([[5.81743618, 6.36415247],
       [0.16574285, 0.23933644],
       [0.44587847, 0.56559804]])